import pandas as pd

CURRENT_WORKING_DIRECTORY = ''
CURRENT_EVALUATED_TOOL_DIRECTORY = ''
CURRENT_EVALUATED_FILE = ''

RUNTIME_MEAN_REPORT = []
RUNTIME_VAR_REPORT = []
MEMORY_MEAN_REPORT = []
MEMORY_VAR_REPORT = []

EVALUATED_FILE_NAMES = []
EVALUATED_FILE_ROW_COUNTS = []
EVALUATED_FILE_PARAMETER_COUNTS = []

FILES_CONTAINING_NOT_ENOUGH_DATA = pd.Series()

# Predictions vs Real
EVALUATED_FILE_PREDICTED_VALUES = []

COMMAND_LINE_ARGS = []
